Update trigger_dispatch.yml

diff --git a/.github/workflows/trigger_dispatch.yml b/.github/workflows/trigger_dispatch.yml
--- a/.github/workflows/trigger_dispatch.yml
+++ b/.github/workflows/trigger_dispatch.yml
@@ -24,14 +24,14 @@ jobs:
             echo "ISSUE_NUMBER is set to $ISSUE_NUMBER"
           fi
           
-      - name: Authenticate GitHub CLI
-        env:
-          PT: ${{ secrets.cmipipo }}
-        run: |
-          echo "${PT}" | gh auth login --with-token || {
-            echo "GitHub authentication failed."
-            exit 1
-          }
+      # - name: Authenticate GitHub CLI
+      #   env:
+      #     PT: ${{ secrets.cmipipo }}
+      #   run: |
+      #     echo "${PT}" | gh auth login --with-token || {
+      #       echo "GitHub authentication failed."
+      #       exit 1
+      #     }
 
       - name: Retrieve Username from Issue
         env:
@@ -76,6 +76,7 @@ jobs:
         env:
           USERNAME: ${{ env.USERNAME }}
           PT: ${{ secrets.cmipipo }}
+          GH_TOKEN: ${{ secrets.cmipipo }}
         run: |
           echo "Adding ${USERNAME} to discussions with read access..."
 
